### ISSUE TITLE
generic minigbm driver

### ISSUE THREAD

**Issue by rsglobal** [lineage-rpi/android_external_minigbm#1]
Hi @KonstaT ,

Early preview of generic back-end is available here:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3440#note_725961

**Comment by KonstaT** [comment]
@rsglobal Awesome, thanks for letting me know. Got this running on Pi 4 with LineageOS 18.0 (Android 11) build with patched Mesa 20.3 and hwcomposer.drm_minigbm.

Seems to work OK browsing through the UI. Crashes with camera and videos. Also experienced some other random crashes (eats up all CMA and had to reboot).

Anyway great start, good to see this running!

**Comment by rsglobal** [comment]
Thanks for testing.
I've pushed recent update. Basic video should work now. Memory leaks should be also fixed.
Can you validate once again?

**Comment by KonstaT** [comment]
Seems overall much more stable. No more random freezes/crashes due to CMA running out.

I didn't get video playback working. Tested with local H.264 files and streaming through browser (m.youtube.com). Using 64-bit build with c2 codecs if that was to matter. Camera also still crashes.

**Comment by rsglobal** [comment]
I've pushed one more update. It seems like video wasn't working due to existing bug in minigbm.  
https://chromium-review.googlesource.com/c/chromiumos/platform/minigbm/+/2589993

**Comment by KonstaT** [comment]
Streaming video through browser (m.youtube.com) works fine now. Trying to play local video files (or record screen capture video) still crashes.
